config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'
  get 'contacts/show'
  get 'contacts/new'
  get 'admin/dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'posts#index'
  post '/like/:post_id' => 'likes#like', as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :posts do
    get "search", on: :collection
  end
  
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :comments, only: [:create]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
  resources :notices, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :posts
  resources :users
end

app/models/notice.rb
class Notice < ApplicationRecord
  validates :content, length: { maximum: 300 }
  validates :released_at, presence: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :login_required
  before_action :admin_required

  def index
    @notices = Notice.all.order(created_at: "DESC")
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    expired_day
    if @notice.save
      flash[:success] = "お知らせを設定しました。"
      redirect_to notices_path
    else
      flash.now[:danger] = "お知らせの設定に失敗しました。"
      render "new"
    end
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    @notice = Notice.find(params[:id])
    @notice.assign_attributes(notice_params)
    expired_day
    if @notice.save
      flash[:success] = "お知らせを編集しました。"
      redirect_to notices_path
    else
      flash.now[:danger] = "お知らせの編集に失敗しました。"
      render "new"
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    if @notice.destroy
      flash[:success] = "お知らせを削除しました。"
      redirect_to notices_path
    end
  end

  private

  def notice_params
    params.require(:notice).permit(:content, :released_at, :expired_at)
  end

  def expired_day
    if notice_params[:expired_at] == "0"
      @notice.expired_at = nil
    else
      weeks = notice_params[:expired_at].to_i
      weeks = weeks * 7
      @notice.expired_at = @notice.released_at + weeks
    end
  end

end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_notice_form.html.erb
<div class="form-group">
    <%= f.label :content, "お知らせ・メッセージ" %>
    <%= f.text_area :content, :class => "form-control form-control-sm",
     :placeholder => "お知らせの内容を入力してください。", style: "height: 300px;" %>
  </div>
  <div class="form-group">
    <%= f.label :released_at, "公開日" %><br>
    <%= f.date_select :released_at, :class => "form-control form-control-sm" %>
  </div>
  <div class="form-group">
    <%= f.label :expired_at, "公開期間(週) ※0を選択すると公開終了日なし(期限なし)で設定されます。" %><br>
    <%= f.select :expired_at, [0,1,2,4,8,12,24,48], :class => "form-control form-control-sm" %>
  </div>
    <%= f.submit "作成", class: "btn btn-primary" %>

app/views/notices/edit.html.erb
<% @page_title = "お知らせの編集" %>
<div class="bg-white container py-4 font-weight-bold">
<h5 class="font-weight-bold text-center"><%= @page_title %></h5>

<%= form_for @notice do |f| %>
   <%= render "notice_form", f: f %>
<% end %>
</div>

app/views/notices/index.html.erb
<% @page_title = "お知らせ管理ボード" %>
<div class="bg-white container py-4">
<h5 class="font-weight-bold text-center"><%= @page_title %></h5>

<% if @notices.present? %>
  <table class="table my-4">
    <thead class="thead-dark">
      <tr>
        <th>お知らせ</th>
        <th>公開日</th>
        <th>公開終了日</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= simple_format notice.content %></td>
        <td><%= notice.released_at.strftime("%Y/%m/%d") %></td>
        <% if notice.expired_at.present? %>
          <td><%= notice.expired_at.strftime("%Y/%m/%d")  %></td>
        <% else %>
          <td>期限なし</td>
        <% end %>
        <td><%= link_to "編集", edit_notice_path(notice) %></td>
        <td><%= link_to "削除", notice, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>設定されたお知らせはありません。</p>
<% end %>
<%= link_to "新規作成", new_notice_path %>
</div>

app/views/notices/new.html.erb
<% @page_title = "お知らせの新規作成" %>
<div class="bg-white container py-4 font-weight-bold">
<h5 class="font-weight-bold text-center"><%= @page_title %></h5>

<%= form_for @notice do |f| %>
   <%= render "notice_form", f: f %>
<% end %>
</div>