config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'
  get 'contacts/show'
  get 'contacts/new'
  get 'admin/dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'posts#index'
  post '/like/:post_id' => 'likes#like', as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :posts do
    get "search", on: :collection
  end
  
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :comments, only: [:create]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
  resources :notices, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, length: { maximum: 150 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200, allow_blank: true }
  validates :content, length: { maximum: 400 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/notice.rb
class Notice < ApplicationRecord
  validates :content, length: { maximum: 300 }
  validates :released_at, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :author, class_name: "User", foreign_key: "user_id"

  has_many :comments, dependent: :destroy 

  has_many_attached :images
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 200, allow_blank: true }
  validates :body, length: { maximum: 400 }
  validates :review, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5, allow_blank: true }
  validates :price, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 2147483647, allow_blank: true }
  validates :user_id, presence: true, numericality: { only_integer: true, allow_blank: true }



  class << self
    def search(query)
      rel = order("title")
      if query.present?
        rel = rel.where("created_at::date = ?","#{query}" )
      end
      rel
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_one_attached :avatar

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :name, presence: true, length: { maximum: 15, allow_blank: true }
  validates :login_id, presence: true, uniqueness: true, length: { minimum: 3, allow_blank: true }
  validates :gender, numericality: true
  validates :introduce, length: { maximum: 100 }
  validates :taste, presence: true, numericality: { allow_blank: true }
  validates :admin, inclusion: { in: [true, false] }

  attr_accessor :current_user
  attr_accessor :current_password

  validates :password, presence: { if: :current_password }

  def age
    date_format = "%Y%m%d"
    (Date.today.strftime(date_format).to_i - birthday&.strftime(date_format).to_i) / 10000
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :login_required
  before_action :admin_required
  
  def dashboard
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables
  def like
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def unlike
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  private
    def set_variables
      @post = Post.find(params[:post_id])
      @id_name = "#like-link-#{@post.id}"
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  # 0~5まで0.5刻みの二次元配列を作成
  def create_review_array
    array = []
    (0..10).each do |n|
      num = n/2.to_f
      array << [num, num]
    end
    array
  end

  def create_user_id_array
    @user_ids = 
    @users.map do |user|
      ["#{user.login_id}" , "#{user.id}"]
    end
    @user_ids
  end

  def create_review_star(post)
    html = []
    comp_star = post.review.to_i
    harf_star = post.review%1
    star_count = 0

    comp_star.times do
      html.push('<i class="fas fa-star"></i>')
      star_count += 1
    end
    if harf_star == 0.5
      html.push('<i class="fas fa-star-half-alt"></i>')
      star_count += 1
    end
    rest_star = 5 - star_count
    rest_star.times do
      html.push('<i class="far fa-star"></i>')
    end
    star_icon = html.join
    star_icon
  end

  def index_image(images)
    if images.attached?
      images.first.variant(auto_orient: true)
      rails_blob_url(images.first)
    else
        ("/assets/hakumai.png")
    end 
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar(user)
    if user.avatar.attached?
      user.avatar.variant(auto_orient: true)
      rails_blob_url(user.avatar)
    else
      if user.gender = 1
        ("/assets/default.jpg")
      else
        ("/assets/default1.jpg")
      end 
    end 
  end

end

app/views/admin/dashboard.html.erb
<% @page_title = "管理者用ページ" %>

<div class="container bg-white py-4">
<h3 class="font-weight-bold mb-4"><%= @page_title %></h3>
  <ul>
    <li><%= link_to "ユーザー管理", users_path %></li>
    <li><%= link_to "メッセージ確認", contacts_path %></li>
    <li><%= link_to "お知らせ", notices_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title + ' - OREMESHI' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('hakumai.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
      var OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "b6e1c706-6344-44e2-a8d9-30f1edef4124",
        });
      });
    </script>
 </head>

  <body>
  <%= render "shared/header" %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg,
       class: "alert-#{name} text-#{name} text-center my-3 container py-3 rounded", id: "flash" %>
    <% end %>
    <div class="container row mx-auto mt-2 p-0">
      <div class="main-wrapper-wrapper col-lg-9 bg-white rounded p-0">
        <div class="main-wrapper">
          <main>  
            <%= yield %>
          </main>
        </div>  
      </div> 
      <div class="col-lg-3 mt-lg-0 mt-4 p-0">
          <%= render 'shared/sidebar' %>
          <div class="mt-4"></div>
          <%= render 'shared/sidebar_menu' %>
          <div class="mt-4"></div>
          <%= render 'shared/sidebar_contact' %>
      </div>
    </div>
    <% if controller.action_name != "new" %>
      <div class="d-block d-lg-none">
      <%= link_to "/posts/new" do %>
        <i class="fas fa-plus bg-primary"></i>
      <% end %>
      </div>
    <% end %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div>
    <ul class="text-left font-weight-normal py-3 alert-warning mb-3">
      <% obj.errors.full_messages.each do |message| %>
        <li class=""><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_user.html.erb
<div class="form-row container">
  <div class="form-group col-lg-6">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control form-control-sm", :placeholder => "俺飯で使用する名前を入力してください。" %>
  </div>

  <% if !controller.controller_name == 'accounts' && !controller.action_name == 'edit' %>
    <div class="form-group col-lg-6">
      <%= f.label :login_id  %>
      <%= f.text_field :login_id, :class => "form-control form-control-sm", :placeholder => "半角英数字3文字以上20字以内。ログイン時に使います。メモしておいてください。" %>
    </div>
  <% end %>

  <% if controller.controller_name == 'users' && controller.action_name == 'new' || controller.action_name == 'create' %>
    <div class="form-group col-lg-12">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, :class  => "form-control form-control-sm", :placeholder => "半角英数字3文字以上20字以内。" %>
    </div>
    <div class="form-group col-lg-12">
      <%= f.label :password_confirmation, "確認用パスワード" %>
      <%= f.password_field :password_confirmation, :class  => "form-control form-control-sm", :placeholder => "確認用の入力欄です。もう一度同じ文字列を入力してください。" %>
    </div>
  <% end %>

  <div class="form-group col-lg-6">
    <%= f.label :gender %><br>
    <div class="form-check form-check-inline">
      <%= f.radio_button :gender, "1", :class => "form-check-input" %>
      <%= f.label :gender, "男性", :value => "1", :class => "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :gender, "2", :class => "form-check-input"%>
      <%= f.label :gender, "女性", :value => "2", :class => "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :gender, "3", :class => "form-check-input" %>
      <%= f.label :gender, "秘密にしておく", :value => "3", :class => "form-check-label" %>
    </div>
  </div>

  <div class="form-row col-lg-6">
    <div class="form-group">
      <%= f.label :birthday %><br>
      <%= f.date_select  :birthday,
                            :start_year => 1900,
                            :end_year => (Time.now.year)
       %>
    </div>
  </div>

  <div class="form-group col-6">
    <%= f.label :prefecture %><br>
    <%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name %>
  </div>

  <div class="form-group col-12">
    <%= f.label :introduce  %>
    <%= f.text_area :introduce, rows: 7, :class => "form-control form-control-sm", :placeholder => "好きな食べ物とか？自由に書いてください" %>
  </div>

  <div class="form-group col-lg-6">
    <%= f.label :taste  %><br>
    <div class="form-check form-check-inline">
      <%= f.radio_button :taste, 1, :class => "form-check-input" %>
      <%= f.label :taste, "甘党",  :class => "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :taste, 2, :class => "form-check-input"%>
      <%= f.label :taste, "辛党",  :class => "form-check-label" %>
    </div>
  </div>

  <div class="form-group col-12">
    <%= f.label :avatar, "プロフィール画像" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group col-12">
  </div>
  <% if current_user&.admin == true %>
      <div class="form-group col-12">
        <%= f.label :admin %><br>
        <div class="form-check form-check-inline">
          <%= f.check_box :admin, :value => true, :class => "form-check-input" %>
          <%= f.label :admin, "管理者", :class => "form-check-label" %>  
        </div>
      </div>
  <% else %>
      <%= f.hidden_field :admin, :value => false %>
  <% end %>

  <div class="ml-4">
    <%= f.submit "登録", class: "btn btn-primary" %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color:#fff200;">
    <div class="container">
      <a class="navbar-brand logo" href="/"><i class="fas fa-utensils"></i>俺飯β</a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "#{current_user.name}", "/account" , :class => "nav-link visible-lg" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", "/users/new", :class => "nav-link visible-lg" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "俺飯を投稿する", "/posts/new", :class => "nav-link btn" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_login_form.html.erb
<%= form_with url: session_path, id: "login-form" do  |f| %>

  <% if flash[:alert] %>
    <p class='text-danger'><%= flash[:alert] %></p>
  <% end %>   

  <div class="mt-4">
    <%= f.label :login_id, 'ログインID：', class: "login-form-label" %>
    <%= f.text_field :login_id, class: "login-form-text" %>
  </div>
  <div class="mt-2">
    <%= f.label :password, 'パスワード：', class: "login-form-label" %>
    <%= f.password_field :password,  class: "login-form-text" %>
  </div>
  <div class="login-btn-wrap">
    <%= f.submit "ログイン",  class: "login-button mb-3"%>
  </div>

<% end %>


<div class="link-to-users-new mb-5">
  <%= link_to "新規ユーザ登録", "/users/new" %>
</div>

app/views/shared/_post_index.html.erb
<div class="row no-gutters">
 <% obj.each do |post| %>
      <div class="mb-4 post-wrapper col-sm-6 bg-white">
          <div class="user-image clearfix">
            <div class="posts-index-user-image float-left" 
                 style="background-image: url(<%= avatar(post.author) %>);"></div>
            <h6 class="user_name float-left pt-3"><%= link_to post.author.name, "/users/#{post.author.id}" %></h6>
          </div>
          <div class="post_image" 
               style="background-image: url(<%= index_image(post.images) %>);"></div>
        <div class="container bg-white pb-3">
          <h3 class="font-weight-bold pt-2 post_title"><%= truncate(post.title, length: 50) %></h3>
          <div class="text-right">
            <p class="post_status">
              <span class="review">満足度: <%= create_review_star(post).html_safe %></span><br>
              <span class="index-comment-icon"><i class="fas fa-comment"></i> <%= post.comments.length %></span>
              <span class="index-like-icon"><i class="fas fa-heart"></i> <%= post.liked_users.count %></span>
            </p>
            <p class="link-to-show"><%= link_to "詳細ページへ", "/posts/#{post.id}" %></p>
            <p class="post_time">投稿日: <%= post.updated_at.strftime("%Y-%m-%d") %></p>
          </div>
        </div>
      </div>
    <% end %>
</div>
<div class="pagination">
  <%= paginate obj %>
</div>  

app/views/shared/_sidebar.html.erb
<div class="side-wrapper rounded">
  <div class="sidebar-title">User</div>
  <div class="container">
    <%= render "shared/login_form" unless current_user %>
    <%= render "shared/sidebar_user" if current_user %>
  </div>
</div>

app/views/shared/_sidebar_contact.html.erb
<% if @notices_side.present? %>
<div class="side-wrapper rounded mt-4">
  <div class="sidebar-title">information</div>
  <div class="container pt-2">
      <ul class="text-left pl-0 text-info" style="list-style: none;">
        <% @notices_side.each do |notice| %>
         <li class="side-menu"><%= notice.content %>  (<%= notice.released_at.strftime("%Y/%m/%d") %>)</li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>


<div class="side-wrapper rounded mt-4">
  <div class="sidebar-title">Contact</div>
  <div class="container pt-2">
      <ul class="text-left pl-0" style="list-style: none;">
        <li class="side-menu"><%= link_to "コンタクトフォーム(バグ報告)", contacts_new_path %></li>
    </ul>
  </div>
</div>

app/views/shared/_sidebar_menu.html.erb
<div class="side-wrapper rounded">
  <div class="sidebar-title">Menu</div>
  <div class="container pt-2">
      <ul class="text-left pl-0" style="list-style: none;">
        <li class="side-menu"><%= link_to "タイムライン", root_path %></li>
        <li class="side-menu"><%= link_to "ユーザー一覧", users_path %></li>
        <li class="side-menu"><a href="">comming soon.....</a></li>
        <% if current_user.present? %>
          <% if current_user.admin? %>
            <li class="side-menu"><%= link_to "管理者ダッシュボード", admin_dashboard_path %></li>
          <% end %>
        <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar_user.html.erb
<div class="user_image_bg text-center" style="background-image: url(<%= avatar(current_user) %>);"></div>
  <h4 class="mt-2 mb-3 font-weight-bold text-center side_menu_user"><%= current_user.name %></h4>
  <ul class="text-left pl-0" style="list-style: none;">
    <li class="side-menu"><%= link_to "俺飯を投稿する", :new_post %></li>
    <li class="side-menu"><%= link_to "マイページ", :account %></a></li>
    <li class="side-menu"><%= link_to "ユーザ情報を編集する", :edit_account %></li>
    <li class="side-menu"><%= link_to "ログアウトする", :session, method: :delete %></li>
  </ul>

app/views/shared/_users_show.html.erb
<div class="py-5 bg-white container">
  <div class="user_image_bg_main_wrapper mb-5">
    <div class="user_image_bg_main mx-auto" style="background-image: url(<%= avatar(@user) %>);"></div>
  </div>
  <div class="container">
    <h4 class="mt-2 mb-3 font-weight-bold"><%= @user.name %></h4>
      <% if @user.taste == 1 %>
        <div class="user_taste sweet"><i class="fas fa-cookie-bite"></i>甘党</div>
      <% elsif @user.taste == 2 %>
        <div class="user_taste hot"><i class="fab fa-hotjar"></i>辛党</div>
      <% end %> 
      <% if controller.kind_of?(AccountsController) %>
          <dl>
            <dt>ログインID</dt>
            <dd><%= @user.login_id %></dd>
          </dl>
      <dl>
        <dt>年齢</dt>
        <dd><%= @user.age %>歳</dd>
      </dl>
      <dl>
        <dt>誕生日</dt>
        <dd><%= @user.birthday.strftime("%m月%d日") %></dd>
      </dl>
      <% end %>
      <dl>
        <dt>性別</dt>
        <% if @user.gender == 1 %>
          <dd>男性</dd>
        <% elsif @user.gender == 2 %>
          <dd>女性</dd>
        <% else %>
          <dd>内緒だよ</dd>
        <% end %>  
      </dl>
      <dl>
        <dt>都道府県</dt>
        <dd><%= @user.prefecture %><dd>
      </dl>
      <dl>
        <dt>自己紹介</dt>
        <dd><%= @user.introduce %></dd>
      </dl>
      <% if controller.kind_of?(AccountsController) %>
      <dl>
        <dt>編集</dt>
        <dd><%= link_to "プロフィールの編集", :edit_account %></dd>
        <dd><%= link_to "パスワードの再設定", :edit_password %></dd>
      </dl>
      <% end %>
      <% if current_user&.admin == true %>
        <dl>
          <dt>編集(管理者)</dt>
          <dd><%= link_to "プロフィールの編集", "/users/#{@user.id}/edit" %></dd>
          <dt>削除(管理者)</dt>
          <dd><%= link_to "ユーザの削除", @user, :method => :delete, data: { confirm: '本当に削除しますか?' } %></dd>
        </dl>
      <% end %>
  </div>
</div>