config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'
  get 'contacts/show'
  get 'contacts/new'
  get 'admin/dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'posts#index'
  post '/like/:post_id' => 'likes#like', as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :posts do
    get "search", on: :collection
  end
  
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :comments, only: [:create]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
  resources :notices, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :posts
  resources :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables
  def like
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def unlike
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  private
    def set_variables
      @post = Post.find(params[:post_id])
      @id_name = "#like-link-#{@post.id}"
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div id="like-link-<%= post.id %>">
<% if current_user.present? %>
  <% if current_user.already_liked?(post) %>
    <%= link_to like_path(post.id), method: :delete, remote: true do %>
      <span class="index-like-icon"><i class="fas fa-heart"></i> <%= post.likes.count %></span><br>
    <% end %>
  <% else %>
    <%= link_to unlike_path(post.id), method: :post, remote: true do %>
      <span class="index-like-icon"><i class="far fa-heart"></i> <%= post.likes.count %></span><br>
    <% end %>
  <% end %>
<% else %>
  <span class="index-like-icon"><i class="far fa-heart"></i> <%= post.likes.count %></span><br>
<% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post)) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post)) %>');