config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'
  get 'contacts/show'
  get 'contacts/new'
  get 'admin/dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'posts#index'
  post '/like/:post_id' => 'likes#like', as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :posts do
    get "search", on: :collection
  end
  
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :comments, only: [:create]
  resources :contacts, only: [:index, :show, :new, :create, :destroy]
  resources :notices, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :posts
  resources :users
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200, allow_blank: true }
  validates :content, length: { maximum: 400 }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :admin_required, only: [:index, :show, :destroy]
  before_action :login_required

  def index
    @contacts = Contact.all.order(created_at: "DESC")
  end

  def show
    @contact = Contact.find(params[:id])
    @user = User.find(@contact.user_id)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "管理者にメッセージを送りました。"
      redirect_to root_path
    else
      flash.now[:danger] = "メッセージの送信に失敗しました。"
      render "new"
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    if @contact.destroy
      flash[:success] = "メッセージを削除しました。"
      redirect_to "/contacts/index"
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:title, :content, :user_id)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<% @page_title = "コンタクト一覧" %>
<div class="container bg-white py-5">
  <h3 class="heading"><%= @page_title %></h3>
  <ul class="">
    <% @contacts.each do |contact| %>
      <li class="py-3">
        <%= contact.created_at.strftime("%Y年%m月%d日") %>
        <%= link_to contact.title, contact %>
      </li>
    <% end %>
  </ul>
</div>

app/views/contacts/new.html.erb
<% @page_title = "コンタクトフォーム" %>

<div class="container bg-white py-5">
<h5 class="font-weight-bold"><%= @page_title %></h5>

<p class="text-info">管理者へ何かメッセージがあれば気軽にご利用ください。バグの報告もこちらからお願いいたします。</p>

<%= form_for @contact do |f| %>
  <%= render "shared/errors", obj: @contact %>
  <div class="form-group">
    <%= f.label :title, "件名" %>
    <%= f.text_field :title, :class => "form-control form-control-sm", :placeholder => "件名を入力してください。" %>
  </div>
  <div class="form-group">
    <%= f.label :content, "メッセージ(400字以内)" %>
    <%= f.text_area :content, :class => "form-control form-control-sm",
     :placeholder => "なにかご要望があれば是非ご気軽にご利用ください。", :style => "height: 400px;" %>
  </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "送信", class: "btn btn-primary" %>
<% end %>

app/views/contacts/show.html.erb
<% @page_title = "#{@contact.title}" %>
<div class="container bg-white py-5">
  <h3 class="heading"><%= @page_title %></h3>
  <ul class="">
    <%= simple_format @contact.content , class: 'posts-body' %>
    <div class="text-right">
      <%= @user.name %><br>
      <%= @contact.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
    </div>
  </ul>
  <%= link_to "削除する", contact_path(@contact.id), method: :delete, data: { confirm: '本当に削除しますか?' } %> |
  <%= link_to "戻る", contacts_path %>
</div>